#!/bin/bash
tf=('tf2' 'steamapps/common/Team\ Fortress\ 2\ Dedicated\ Server/' 'cp_5gorge')
declare -a nd=('nd' 'steamapps/common/Nuclear\\ Dawn/' 'downtown');
declare -a ins=('insurgency' 'steamapps/common/Insurgency\\ Dedicated\\ Server/' 'market');

selected=("${tf[@]}")

cd ../steamcmd/
./steamcmd.sh +runscript ../tpgameserver/${selected[0]}/update.txt
echo ${selected[1]} and stuff
eval cd "${selected[1]}"
cd steamapps
./srcds_run -console +maxplayers 24 +map ${selected[2]}
#screen -A -m -d -S serverName
